// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive.dart';
import 'package:taskflow/models/task.dart';
import 'package:taskflow/models/task_enums.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(SortOptionAdapter());
    registerAdapter(TaskAdapter());
    registerAdapter(TaskCategoryAdapter());
    registerAdapter(TaskStatusAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(SortOptionAdapter());
    registerAdapter(TaskAdapter());
    registerAdapter(TaskCategoryAdapter());
    registerAdapter(TaskStatusAdapter());
  }
}
